name: Create Release

on:
  push:

jobs:
  setTag:
    name: Set tag
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ github.event.inputs.version }}
          message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: windows-latest
    needs: setTag
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         prerelease: false
