on:
  push:

name: Create Release

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d at %H/%M')"
      - name: Create Release
        run: gh release create ${{ steps.date.outputs.date }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
